### ISSUE TITLE
Error with Mechanize module

### ISSUE THREAD

**Issue by hansdg1** [doug1/cox-data-usage#1]
Hi, I see that the last update to this code was fairly recent, Aug 5th. Does this code still work for the current version of their site? I forked the code, and added the ability to use a config file to store the username/password, but I keep getting the following error.  I even undid my changes and still get the error with your code.  What version of Mechanize are you using?

HTML::Form::parse: No $base_uri provided at /usr/share/perl5/WWW/Mechanize.pm line 2759.

Thanks!

**Comment by doug1** [comment]
@hansdg1 Well, it's been 5 years, and I just updated the script to work with the latest Cox website re-design, now with more JSON.  If you're still interested, please give it a try.  Thanks!

**Comment by hansdg1** [comment]
Thankfully I'm no longer a customer of Cox, but I appreciate the followup
